version: '3'
services:
    mysql:
      container_name: some-mysql
      image: mysql/mysql-server:5.7
      environment:
        MYSQL_ROOT_PASSWORD: hellokoding
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: account
      ports:
        - "33062:3306"
      volumes:
        - db_data:/var/lib/mysql
      restart: always

    app:
      restart: always
      build: ./app
      working_dir: /app
      volumes:
        - ./app:/app
        - ~/.m2:/root/.m2
      ports:
        - "8080:8080"
      command: mvn clean spring-boot:run
      depends_on:
        - mysql

volumes:
  db_data:
